apiVersion: v1
kind: Pod
metadata:
  name: hello-world-python
spec:
  containers:
  - name: hello-world-python
    image: tdharkar/pythonapp:tagname
    ports:
    - containerPort: 5050
    resources:
      requests:
        memory: "250Mi"
        cpu: "200m"
