apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: hello-world
    ports:
    - containerPort: 5050
    resources:
      requests:
        memory: "250Mi"
        cpu: "200m"
